name: cpp

on:
  push:
    paths-ignore:
      - '**.md'
      - 'rust/**'
      - 'js/**'
      - 'python/**'
      - '.github/workflows/python.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'rust/**'
      - 'js/**'
      - 'python/**'
      - '.github/workflows/python.yml'

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}-${{ matrix.configuration }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc
          - windows-mingw

        configuration:
          - Debug
          - Release

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc
            env:
              CMAKE_OPTIONS: "-DRPC_CORE_TEST_PLUGIN=ON"

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            env:
              CMAKE_OPTIONS: "-DRPC_CORE_TEST_PLUGIN=ON"

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
            env:
              BIN_SUFFIX: ".exe"

          - toolchain: windows-mingw
            os: windows-latest
            compiler: mingw
            env:
              BIN_SUFFIX: ".exe"
              CMAKE_OPTIONS: "-G \"MinGW Makefiles\""

    steps:
      - uses: actions/checkout@v4

      - name: Init ASIO
        run: git clone https://github.com/chriskohlhoff/asio.git -b asio-1-32-0 --depth=1

      - name: Init nlohmann/json
        run: |
          cmake -E make_directory thirdparty/nlohmann
          python -c "import urllib.request; urllib.request.urlretrieve('https://github.com/nlohmann/json/releases/download/v3.11.2/json.hpp', 'thirdparty/nlohmann/json.hpp')"

      - name: Configure (${{ matrix.configuration }})
        env:
          ASIO_PATH: asio/asio/include
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DRPC_CORE_TEST_ASIO=ON ${{ matrix.env.CMAKE_OPTIONS }}

      - name: Init thirdparty
        if: matrix.os != 'windows-latest'
        run: cmake --build build --target rpc_core_test_init

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build --config ${{ matrix.configuration }} -j

      - name: Windows-MSVC Compatible
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        working-directory: build
        run: Move-Item -Path .\${{ matrix.configuration }}\* -Destination .\

      - name: Test
        working-directory: build
        run: ./rpc_core_test${{ matrix.env.BIN_SUFFIX }}

      - name: Test ASIO TCP RPC
        working-directory: build
        run: ./rpc_core_test_asio_tcp_rpc${{ matrix.env.BIN_SUFFIX }}
