name: rust

on:
  push:
    paths-ignore:
      - '**.md'
      - 'include/**'
      - 'test/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'include/**'
      - 'test/**'

env:
  RUST_BACKTRACE: 1

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: cargo fmt -- --check
        working-directory: rust
        run: cargo fmt -- --check

      - name: build
        working-directory: rust
        run: cargo build

      - name: Test all features
        working-directory: rust
        run: cargo test --all-features
